version: "3.8"
services:
  frontend:
    build: ./iot-management-sys
    container_name: iot_frontend_ljx
    ports:
      - "8080:8080"
    volumes:
      - ./iot-management-sys:/app
      - /app/node_modules
  backend:
    build: ./iot-express
    container_name: iot_backend_ljx
    ports:
      - "3000:3000"
    volumes:
      - ./iot-express:/app
      - /app/node_modules
    stdin_open: true
    tty: true
